name: Container Building

on:
  push:
    paths:
      - 'slim-pipenv/**/*'
      - '.github/workflows/container-build.yml'

jobs:
  imagebuild:
    name: Multistage build of container in multiple architectures
    defaults:
      run:
        working-directory: ./slim-pipenv
    env:
      DOCKERHUB_REPO: curryeleison/python-container-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU to fetch amd64 and arm64
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm64
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker meta - set up image tags and labels
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKERHUB_REPO }}
          tags: |
            type=sha
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./slim-pipenv
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
