name: Python container to demonstrate tests in CICD

on:
  push:
    paths:
      - 'slim-testing/**/*'
      - '.github/workflows/container-test.yml'

jobs:
  containertestaction:
    name: Build image, but run testing before pushing
    defaults:
      run:
        working-directory: ./slim-testing
    env:
      DOCKERHUB_REPOSITORY: curryeleison/python-testing-demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build test target
        uses: docker/build-push-action@v2
        with:
          context: ./slim-testing
          push: false
          load: true
          target: test
          tags: ${{ env.DOCKERHUB_REPOSITORY }}:test
      - name: Set up test results dir
        id: testsetup
        run: |
          mkdir -p $PWD/test-results/
          chmod 777 $PWD/test-results/
          echo "::set-output name=testdir::$PWD/test-results/"
      - name: Run linting and tests
        run: |
          docker run --rm -v ${{ steps.testsetup.outputs.testdir }}:"/app/test-results/" ${{ env.DOCKERHUB_REPOSITORY }}:test

      # EnricoMi action - https://github.com/marketplace/actions/publish-unit-test-results
      # Nice about collapsing detailed test results, detailed instructions, supports forked repos
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          check_name: pytest-results
          files: ${{ steps.testsetup.outputs.testdir }}**/*.xml

      # Dorny action: https://github.com/marketplace/actions/test-reporter
      # Accepts many input formats, good documentation of forked repos
      # - name: Test Report -- dorny action # Accepts many input formats 
      #   uses: dorny/test-reporter@v1
      #   if: success() || failure()    # run this step even if previous step failed
      #   with:
      #     name: pytest
      #     path: ${{ steps.testsetup.outputs.testdir }}**/*.xml
      #     reporter: java-junit

      - name: Branch information
        id: branchinfo
        run: |
          echo "::set-output name=isdefault::$([[ ${GITHUB_REF##*/} == "${{ github.event.repository.default_branch }}" ]] && echo true || echo false)"
      - name: Set up QEMU to fetch amd64 and arm64
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: amd64,arm64
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Docker meta - set up image tags and labels
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKERHUB_REPOSITORY }}
          tags: |
            type=sha
          flavor: |
            latest=${{ steps.branchinfo.outputs.isdefault }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./slim-testing
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
