name: Boto3 container demo build and push

on:
  push:
    paths:
      - 'alpine-boto3-ecr/**/*'
      - '.github/workflows/ecr-build.yml'
jobs:
  boto3imagebuildpush:
    name: Build Boto3 image
    defaults:
      run:
        working-directory: ./alpine-boto3-ecr
    env:
      AWS_DEFAULT_REGION: eu-west-1
      ECR_REPOSITORY: alpine-boto3-demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Branch information
        id: branchinfo
        run: |
          echo "::set-output name=isdefault::$([[ ${GITHUB_REF##*/} == "${{ github.event.repository.default_branch }}" ]] && echo true || echo false)"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm64
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.AWS_ECR_PUSH_ROLE_ARN }}
          # role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
          role-duration-seconds: 3600
          role-session-name: EcrBuildWorkerImageSession
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Image names
        id: buildinfo
        run: |
          echo "::set-output name=image_repo::"${{ steps.login-ecr.outputs.registry }}"/$ECR_REPOSITORY"
          echo "::set-output name=image_repo_shatag::"${{ steps.login-ecr.outputs.registry }}"/$ECR_REPOSITORY:"${{ github.sha }}
      - name: Build image and tag it
        run: |
          docker build --load -t ${{ steps.buildinfo.outputs.image_repo_shatag }} .
      - name: Tag as latest and push repo if we are on default branch
        if: ${{ steps.branchinfo.outputs.isdefault == 'true' }}
        run: |
          docker build --push --platform=linux/amd64,linux/arm64 -t ${{ steps.buildinfo.outputs.image_repo_shatag }} .
          docker tag ${{ steps.buildinfo.outputs.image_repo_shatag }} ${{ steps.buildinfo.outputs.image_repo }}:latest
          docker push ${{ steps.buildinfo.outputs.image_repo }}:latest
